"""initial StoryWeave schema

Revision ID: 9cde937f7a48
Revises: 
Create Date: 2026-10-01 10:08:38.647070
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '9cde937f7a48'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('phonics_pattern',
    sa.Column('phonics_pattern_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('example_words', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('sequence_order > 0', name='ck_phonics_pattern_sequence_order'),
    sa.PrimaryKeyConstraint('phonics_pattern_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('sequence_order', name='uq_phonics_pattern_sequence_order')
    )
    op.create_table('vocabulary_word',
    sa.Column('vocabulary_word_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('is_sight_word', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(word) > 0', name='ck_vocabulary_word_not_empty'),
    sa.CheckConstraint('word = lower(word)', name='ck_vocabulary_word_lowercase'),
    sa.CheckConstraint('word = trim(word)', name='ck_vocabulary_word_trimmed'),
    sa.PrimaryKeyConstraint('vocabulary_word_id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('caregiver_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('child',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('grade_level', sa.SmallInteger(), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('[]'::jsonb)"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('grade_level BETWEEN 1 AND 3', name='ck_child_grade_level'),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_word_pattern',
    sa.Column('vocabulary_word_id', sa.Integer(), nullable=False),
    sa.Column('phonics_pattern_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phonics_pattern_id'], ['phonics_pattern.phonics_pattern_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_word_id'], ['vocabulary_word.vocabulary_word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vocabulary_word_id', 'phonics_pattern_id')
    )
    op.create_table('articulation_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('phoneme', sa.String(length=32), nullable=True),
    sa.Column('phonics_pattern_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('phoneme IS NOT NULL OR phonics_pattern_id IS NOT NULL', name='ck_articulation_flag_target'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phonics_pattern_id'], ['phonics_pattern.phonics_pattern_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phonics_mastery',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('phonics_pattern_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attempts_count >= 0', name='ck_phonics_mastery_attempts'),
    sa.CheckConstraint('correct_count >= 0 AND correct_count <= attempts_count', name='ck_phonics_mastery_correct_count'),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 1', name='ck_phonics_mastery_score'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phonics_pattern_id'], ['phonics_pattern.phonics_pattern_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('child_id', 'phonics_pattern_id')
    )
    op.create_index('ix_phonics_mastery_pattern_score', 'phonics_mastery', ['phonics_pattern_id', 'mastery_score'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'validated', 'approved')", name='ck_story_status'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name='ck_reading_session_status'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_session_child_started', 'reading_session', ['child_id', 'started_at'], unique=False)
    op.create_table('story_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('line_number > 0', name='ck_story_line_positive_number'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'line_number', name='uq_story_line_number')
    )
    op.create_table('story_pattern',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('phonics_pattern_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phonics_pattern_id'], ['phonics_pattern.phonics_pattern_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'phonics_pattern_id')
    )
    op.create_table('reading_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reading_session_id', sa.UUID(), nullable=False),
    sa.Column('story_line_id', sa.UUID(), nullable=False),
    sa.Column('word_index', sa.SmallInteger(), nullable=False),
    sa.Column('expected_word', sa.String(length=100), nullable=False),
    sa.Column('recognized_word', sa.String(length=100), nullable=True),
    sa.Column('vocabulary_word_id', sa.Integer(), nullable=True),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("result_status IN ('mastered', 'shaky', 'missed')", name='ck_reading_attempt_result_status'),
    sa.CheckConstraint('word_index > 0', name='ck_reading_attempt_word_index'),
    sa.ForeignKeyConstraint(['reading_session_id'], ['reading_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_line_id'], ['story_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_word_id'], ['vocabulary_word.vocabulary_word_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_attempt_session_line', 'reading_attempt', ['reading_session_id', 'story_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reading_attempt_session_line', table_name='reading_attempt')
    op.drop_table('reading_attempt')
    op.drop_table('story_pattern')
    op.drop_table('story_line')
    op.drop_index('ix_reading_session_child_started', table_name='reading_session')
    op.drop_table('reading_session')
    op.drop_table('story')
    op.drop_index('ix_phonics_mastery_pattern_score', table_name='phonics_mastery')
    op.drop_table('phonics_mastery')
    op.drop_table('articulation_flag')
    op.drop_table('vocabulary_word_pattern')
    op.drop_table('child')
    op.drop_table('caregiver_session')
    op.drop_table('vocabulary_word')
    op.drop_table('phonics_pattern')
    op.drop_table('caregiver')
    # ### end Alembic commands ###